node {
    git url: 'https://github.com/saivadrevu2287/CDCD1.git'

    // Get Artifactory server instance, defined in the Artifactory Plugin administration page.
    def server = Artifactory.server SERVER_ID

    // Create the upload spec.
    def uploadSpec = """{
        "files": [
                {
                    "pattern": "jenkins-pipeline-example/resources/CentOS-7-x86_64-GenericCloud-1510.qcow2",
                    "target": "libs-snapshot-local",
                   "props": "p1=v1;p2=v2"
                }
            ]
        }"""

    // Upload to Artifactory.
    def buildInfo1 = server.upload spec: uploadSpec

    // Create the download spec.
    def downloadSpec = """{
        "files": [
                {
                    "pattern": "libs-snapshot-local/*(GenericCloud).qcow2",
                    "target": "/home/centos/{1}/",
                    "props": "p1=v1;p2=v2"
                }
            ]
        }"""

    // Download from Artifactory.
    def buildInfo2 = server.download spec: downloadSpec

    // Merge the upload and download build-info objects.
   // buildInfo1.append buildInfo2

    // Publish the build to Artifactory
   // server.publishBuildInfo buildInfo1
}
